import { defineConfig } from "vitest/config"

export default defineConfig({
  test: {
    globals: true,
    environment: "node",
    include: ["_tests_/src/**/*.{test,spec}.ts"],
    exclude: ["**/node_modules/**", "**/dist/**", "**/e2e/**", "**/bench/**", "_tests_/scripts/**"],
    coverage: {
      provider: "v8",
      reportsDirectory: "./coverage",
      include: [
        "src/**/*",
        "scripts/lib/bootstrap/backup.ts",
        "scripts/lib/bootstrap/docs-generator.ts",
        "scripts/lib/bootstrap/engine.ts",
        "scripts/lib/bootstrap/index.ts",
        "scripts/lib/bootstrap/manifest.ts",
        "scripts/lib/bootstrap/presets.ts",
        "scripts/lib/bootstrap/prompts.ts",
        "scripts/lib/bootstrap/readme-generator.ts",
        "scripts/lib/bootstrap/validator.ts",
        "scripts/lib/bootstrap/yaml-utils.ts",
        "scripts/lib/cache.ts",
        "scripts/lib/detector.ts",
        "scripts/lib/next-termux.ts",
        "scripts/lib/termux.ts",
        "scripts/lib/security.ts",
        "scripts/lib/logger.ts",
        "scripts/lib/errors.ts",
        "scripts/lib/cicd.ts",
        "scripts/lib/preview.ts",
        "scripts/lib/bundle.ts",
        "scripts/lib/automerge.ts",
        "scripts/lib/quality.ts",
        "scripts/lib/a11y.ts",
        "scripts/lib/visual.ts",
        "scripts/lib/bench.ts",
        "scripts/build.ts",
        "scripts/check.ts",
        "scripts/check-cicd.ts",
        "scripts/check-determinism.ts",
        "scripts/check-env.ts",
        "scripts/check-security.ts",
        "scripts/dev.ts",
        "scripts/execute.ts",
        "scripts/setup.ts",
        "scripts/verify-docs.ts",
      ],
      exclude: [
        "**/*.test.ts",
        "**/*.spec.ts",
        "**/__tests__/**",
        "node_modules/**",
        "dist/**",
        "_tests_/**",
        "**/*.d.ts",
      ],
      thresholds: {
        statements: 85,
        branches: 85,
        functions: 85,
        lines: 85,
      },
      reporter: ["text", "json-summary", "lcov", "html"],
    },
  },
})
