/**
 * Feature Manifest — 宣言的な機能定義マニフェスト
 * 各機能が「関連ファイル・依存関係・scripts・CIジョブ・競合」を宣言
 */

import type { FeatureDefinition, ProjectTypeDefinition } from "./types.ts"

export const FEATURES: Record<string, FeatureDefinition> = {
  docker: {
    id: "docker",
    name: "Docker",
    description: "Dockerfile, docker-compose.yml, .dockerignore — containerized dev & prod",
    group: "dev-infra",
    defaultEnabled: true,
    icon: "🐳",
    impact: "Adds container support, requires Docker daemon",
    files: ["Dockerfile", ".dockerignore", "docker-compose.yml"],
    scripts: ["docker:build", "docker:run", "docker:compose", "docker:compose:down"],
    ciSteps: ["Docker"],
  },
  devcontainer: {
    id: "devcontainer",
    name: "Dev Container",
    description: ".devcontainer/ for VSCode remote containers & Codespaces",
    group: "dev-infra",
    defaultEnabled: true,
    icon: "📦",
    impact: "Enables VSCode Dev Containers, no extra deps",
    files: [".devcontainer/**"],
  },
  termux: {
    id: "termux",
    name: "Termux Optimization",
    description: "Android Termux detection and Webpack fallback for Next.js",
    group: "dev-infra",
    defaultEnabled: true,
    icon: "📱",
    impact: "Auto-detects Termux, forces Webpack for Next.js stability",
    files: [],
    ciSteps: ["Termux", "environment info"],
  },
  vitest: {
    id: "vitest",
    name: "Vitest",
    description: "Unit testing with Vitest + TSX runner",
    group: "testing-quality",
    defaultEnabled: true,
    icon: "🧪",
    impact: "Adds fast unit testing, ~50MB",
    files: ["vitest.config.ts", "_tests_/src/**"],
    dependencies: ["vitest", "@vitest/coverage-v8", "tsx"],
    scripts: ["test", "test:unit"],
    ciSteps: ["Unit tests"],
  },
  playwright: {
    id: "playwright",
    name: "Playwright (E2E)",
    description: "E2E testing with Playwright — cross-browser",
    group: "testing-quality",
    defaultEnabled: true,
    icon: "🎭",
    impact: "Adds E2E testing, ~500MB browsers on install",
    files: ["playwright.config.ts", "playwright-report/**", "test-results/**"],
    dependencies: ["@playwright/test"],
    scripts: ["test:e2e"],
    ciJobs: ["e2e"],
    ciSteps: ["E2E", "Playwright"],
  },
  coverage: {
    id: "coverage",
    name: "Coverage (85% threshold)",
    description: "Coverage reporting with v8, threshold 85%",
    group: "testing-quality",
    defaultEnabled: true,
    icon: "📊",
    impact: "Enforces 85% coverage, requires Vitest",
    files: ["coverage/**"],
    scripts: ["test:coverage"],
    ciSteps: ["Coverage", "coverage"],
    requires: ["vitest"],
  },
  cspell: {
    id: "cspell",
    name: "CSpell (spell check)",
    description: "Spell checking for docs and code",
    group: "testing-quality",
    defaultEnabled: true,
    icon: "🔤",
    impact: "Catches typos, ~20MB dict",
    files: ["cspell.json"],
    dependencies: ["cspell"],
    scripts: ["cspell"],
    ciSteps: ["CSpell", "spell"],
  },
  knip: {
    id: "knip",
    name: "Knip (unused code)",
    description: "Unused code & dependency detection",
    group: "testing-quality",
    defaultEnabled: true,
    icon: "🧹",
    impact: "Finds dead code, no runtime impact",
    files: ["knip.json"],
    dependencies: ["knip"],
    scripts: ["knip"],
    ciSteps: ["Knip"],
  },
  publint: {
    id: "publint",
    name: "Publint (package quality)",
    description: "npm package quality lint — for libraries",
    group: "testing-quality",
    defaultEnabled: true,
    icon: "📦",
    impact: "Ensures package is publishable",
    files: [],
    dependencies: ["publint"],
    scripts: ["publint"],
    ciSteps: ["Publint", "publint"],
  },
  "size-limit": {
    id: "size-limit",
    name: "Size Limit (bundle size)",
    description: "Bundle size tracking with @size-limit/preset-small-lib",
    group: "testing-quality",
    defaultEnabled: true,
    icon: "📏",
    impact: "Tracks bundle size, for libraries",
    files: [],
    dependencies: ["size-limit", "@size-limit/preset-small-lib"],
    scripts: ["size", "size:why"],
    ciSteps: ["Size Limit", "size-limit", "Size"],
  },
  determinism: {
    id: "determinism",
    name: "Determinism Guard",
    description: "Forbidden API detection (Math.random, Date.now in pure layer)",
    group: "testing-quality",
    defaultEnabled: true,
    icon: "🔒",
    impact: "Prevents non-deterministic code in pure functions",
    files: [
      "scripts/check-determinism.ts",
      "_tests_/src/scripts/check-cover.test.ts",
      "_tests_/src/scripts/check-env.test.ts",
      "_tests_/src/scripts/check-extra.test.ts",
      "_tests_/src/scripts/deter-cover.test.ts",
      "_tests_/src/scripts/deter-extra.test.ts",
    ],
    scripts: ["check:determinism"],
    ciSteps: ["Determinism", "determinism"],
  },
  husky: {
    id: "husky",
    name: "Husky + lint-staged",
    description: "Pre-commit hooks — lint & spell check staged files",
    group: "git-workflow",
    defaultEnabled: true,
    icon: "🐶",
    impact: "Runs lint on commit, fast",
    files: [".husky/**"],
    dependencies: ["husky", "lint-staged"],
    scripts: ["prepare"],
  },
  commitlint: {
    id: "commitlint",
    name: "Commitlint + Commitizen",
    description: "Conventional Commits enforcement",
    group: "git-workflow",
    defaultEnabled: true,
    icon: "📝",
    impact: "Enforces commit message format",
    files: ["commitlint.config.js"],
    dependencies: [
      "@commitlint/cli",
      "@commitlint/config-conventional",
      "commitizen",
      "cz-conventional-changelog",
    ],
    scripts: ["commit"],
  },
  "github-templates": {
    id: "github-templates",
    name: "GitHub Templates",
    description: "Issue templates, PR template, CODEOWNERS, SECURITY, labeler",
    group: "git-workflow",
    defaultEnabled: true,
    icon: "🏷️",
    impact: "Adds GitHub community health files",
    files: [
      ".github/ISSUE_TEMPLATE/**",
      ".github/PULL_REQUEST_TEMPLATE.md",
      ".github/CODEOWNERS",
      ".github/SECURITY.md",
      ".github/FUNDING.yml",
      ".github/labeler.yml",
      ".github/workflows/label.yml",
    ],
  },
  renovate: {
    id: "renovate",
    name: "Renovate",
    description: "Automated dependency updates — grouped, scheduled",
    group: "git-workflow",
    defaultEnabled: true,
    icon: "🤖",
    impact: "Auto-updates deps weekly",
    files: ["renovate.json"],
  },
  "stale-bot": {
    id: "stale-bot",
    name: "Stale Bot",
    description: "Auto-close stale issues/PRs after 60/30 days",
    group: "git-workflow",
    defaultEnabled: true,
    icon: "⏰",
    impact: "Keeps issues tidy",
    files: [".github/workflows/stale.yml"],
  },
  changesets: {
    id: "changesets",
    name: "Changesets",
    description: "Versioning and release PR automation",
    group: "release",
    defaultEnabled: true,
    icon: "🦋",
    impact: "Adds Version Packages PR & release workflow",
    files: [".changeset/**", ".github/workflows/release.yml"],
    dependencies: ["@changesets/cli", "@changesets/changelog-github"],
    scripts: ["changeset", "changeset:version", "changeset:publish"],
    ciJobs: [],
  },
}

export const PROJECT_TYPES: Record<string, ProjectTypeDefinition> = {
  plain: {
    id: "plain",
    name: "Plain TypeScript",
    description: "Library or plain TS project (tsc only) — minimal, publishable",
    icon: "📚",
    filesToCreate: [],
    filesToRemove: [
      "vite.config.ts",
      "vite.config.js",
      "vite.config.mjs",
      "vite.config.cjs",
      "vite.config.mts",
      "next.config.js",
      "next.config.mjs",
      "next.config.ts",
      "next.config.cjs",
      "turbo.json",
      "playwright.config.ts",
      "playwright.config.js",
      "index.html",
      "app/**",
      "apps/**",
      "packages/**",
    ],
    scriptsToAdd: {},
    defaultFeatures: {
      playwright: false,
    },
  },
  vite: {
    id: "vite",
    name: "Vite",
    description: "Vite SPA (React, Vue, etc) — fast HMR, optimized build",
    icon: "⚡",
    filesToCreate: [
      {
        path: "vite.config.ts",
        fromExample: "docs/examples/vite.config.example.ts",
        overwrite: false,
      },
      {
        path: "index.html",
        content:
          '<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8" />\n  <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n  <title>Vite App</title>\n</head>\n<body>\n  <div id="app"></div>\n  <script type="module" src="/src/main.ts"></script>\n</body>\n</html>\n',
        overwrite: false,
      },
      {
        path: "src/main.ts",
        content:
          'import "./index.ts"\nconsole.log("Vite app started")\nconst app = document.getElementById("app")\nif (app) app.textContent = "Hello from Vite + Template Bootstrap!"\n',
        overwrite: false,
      },
      {
        path: "src/vite-env.d.ts",
        content: '/// <reference types="vite/client" />\n',
        overwrite: false,
      },
    ],
    filesToRemove: [
      "next.config.js",
      "next.config.mjs",
      "next.config.ts",
      "next.config.cjs",
      "turbo.json",
      "app/**",
      "apps/**",
      "packages/**",
    ],
    dependenciesToAdd: [{ name: "vite", version: "^7.0.0", dev: true }],
    scriptsToAdd: {
      "dev:vite": "pnpm exec vite",
      "build:vite": "pnpm exec vite build",
      preview: "pnpm exec vite preview",
    },
    defaultFeatures: {
      publint: false,
      "size-limit": false,
    },
  },
  next: {
    id: "next",
    name: "Next.js",
    description: "Next.js SSR/SSG app — React 19, Turbopack, Termux-aware",
    icon: "🔼",
    filesToCreate: [
      {
        path: "next.config.mjs",
        fromExample: "docs/examples/next.config.example.mjs",
        overwrite: false,
      },
      {
        path: "app/page.tsx",
        content:
          'export default function Page() {\n  return (\n    <main style={{ padding: "2rem", fontFamily: "system-ui" }}>\n      <h1>Hello from Next.js + Template Bootstrap!</h1>\n      <p>Edit <code>app/page.tsx</code> to get started.</p>\n    </main>\n  )\n}\n',
        overwrite: false,
      },
      {
        path: "app/layout.tsx",
        content:
          'export const metadata = { title: "Next.js App", description: "Bootstrapped with template" }\n\nexport default function RootLayout({ children }: { children: React.ReactNode }) {\n  return (\n    <html lang="en">\n      <body style={{ margin: 0, fontFamily: "system-ui" }}>{children}</body>\n    </html>\n  )\n}\n',
        overwrite: false,
      },
      {
        path: "app/globals.css",
        content: "* { box-sizing: border-box; }\nbody { margin: 0; padding: 0; }\n",
        overwrite: false,
      },
    ],
    filesToRemove: [
      "vite.config.ts",
      "vite.config.js",
      "vite.config.mjs",
      "vite.config.cjs",
      "vite.config.mts",
      "turbo.json",
      "index.html",
      "apps/**",
      "packages/**",
    ],
    dependenciesToAdd: [
      { name: "next", version: "^16.0.0", dev: false },
      { name: "react", version: "^19.0.0", dev: false },
      { name: "react-dom", version: "^19.0.0", dev: false },
      { name: "@types/react", version: "^19.0.0", dev: true },
      { name: "@types/react-dom", version: "^19.0.0", dev: true },
    ],
    scriptsToAdd: {
      "dev:next": "pnpm exec next dev",
      "build:next": "pnpm exec next build",
      "start:next": "pnpm exec next start",
    },
    defaultFeatures: {
      publint: false,
      "size-limit": false,
    },
  },
  monorepo: {
    id: "monorepo",
    name: "Monorepo (Turborepo)",
    description: "PNPM workspace + Turborepo — packages/* and apps/*",
    icon: "🏗️",
    filesToCreate: [
      {
        path: "pnpm-workspace.yaml",
        content: 'packages:\n  - "packages/*"\n  - "apps/*"\n',
        overwrite: false,
      },
      {
        path: "turbo.json",
        content:
          '{\n  "$schema": "https://turbo.build/schema.json",\n  "ui": "tui",\n  "tasks": {\n    "build": {\n      "dependsOn": ["^build"],\n      "outputs": ["dist/**", ".next/**", "!.next/cache/**"]\n    },\n    "dev": {\n      "cache": false,\n      "persistent": true\n    },\n    "lint": {},\n    "typecheck": {},\n    "test:unit": {},\n    "test:coverage": {},\n    "check": {\n      "dependsOn": ["^check"]\n    }\n  }\n}\n',
        overwrite: false,
      },
      {
        path: "packages/ui/package.json",
        content:
          '{\n  "name": "@repo/ui",\n  "version": "0.0.0",\n  "private": true,\n  "main": "./src/index.ts",\n  "types": "./src/index.ts",\n  "scripts": {\n    "lint": "biome lint .",\n    "typecheck": "tsc --noEmit",\n    "build": "tsc"\n  }\n}\n',
        overwrite: false,
      },
      {
        path: "packages/ui/src/index.ts",
        content: 'export const shared = "shared ui"\n',
        overwrite: false,
      },
      {
        path: "apps/web/package.json",
        content:
          '{\n  "name": "web",\n  "private": true,\n  "scripts": {\n    "dev": "pnpm exec vite --port 3000",\n    "build": "pnpm exec vite build",\n    "lint": "biome lint .",\n    "typecheck": "tsc --noEmit"\n  }\n}\n',
        overwrite: false,
      },
    ],
    filesToRemove: [
      "vite.config.ts",
      "vite.config.js",
      "vite.config.mjs",
      "next.config.js",
      "next.config.mjs",
      "next.config.ts",
      "index.html",
      "app/**",
    ],
    dependenciesToAdd: [{ name: "turbo", version: "^2.0.0", dev: true }],
    scriptsToAdd: {
      "dev:turbo": "pnpm exec turbo dev",
      "build:turbo": "pnpm exec turbo build",
      "check:turbo": "pnpm exec turbo run check",
    },
    defaultFeatures: {},
  },
  "next-monorepo": {
    id: "next-monorepo",
    name: "Next.js + Monorepo",
    description: "Next.js app inside Turborepo — apps/web (Next.js) + packages/ui",
    icon: "🔼🏗️",
    filesToCreate: [
      {
        path: "pnpm-workspace.yaml",
        content: 'packages:\n  - "packages/*"\n  - "apps/*"\n',
        overwrite: false,
      },
      {
        path: "turbo.json",
        content:
          '{\n  "$schema": "https://turbo.build/schema.json",\n  "ui": "tui",\n  "tasks": {\n    "build": {\n      "dependsOn": ["^build"],\n      "outputs": ["dist/**", ".next/**", "!.next/cache/**"]\n    },\n    "dev": {\n      "cache": false,\n      "persistent": true\n    },\n    "lint": {},\n    "typecheck": {},\n    "test:unit": {},\n    "test:coverage": {}\n  }\n}\n',
        overwrite: false,
      },
      {
        path: "apps/web/next.config.mjs",
        fromExample: "docs/examples/next.config.example.mjs",
        overwrite: false,
      },
      {
        path: "apps/web/app/page.tsx",
        content:
          'export default function Page() {\n  return (\n    <main style={{ padding: "2rem" }}>\n      <h1>apps/web — Next.js + Monorepo</h1>\n      <p>Edit <code>apps/web/app/page.tsx</code></p>\n    </main>\n  )\n}\n',
        overwrite: false,
      },
      {
        path: "apps/web/app/layout.tsx",
        content:
          'export default function RootLayout({ children }: { children: React.ReactNode }) {\n  return <html lang="en"><body>{children}</body></html>\n}\n',
        overwrite: false,
      },
      {
        path: "apps/web/package.json",
        content:
          '{\n  "name": "web",\n  "private": true,\n  "scripts": {\n    "dev": "next dev --port 3000",\n    "build": "next build",\n    "lint": "biome lint .",\n    "typecheck": "tsc --noEmit"\n  },\n  "dependencies": {\n    "next": "^16.0.0",\n    "react": "^19.0.0",\n    "react-dom": "^19.0.0"\n  },\n  "devDependencies": {\n    "@types/react": "^19.0.0",\n    "@types/react-dom": "^19.0.0",\n    "@types/node": "^24.0.0"\n  }\n}\n',
        overwrite: false,
      },
      {
        path: "packages/ui/package.json",
        content:
          '{\n  "name": "@repo/ui",\n  "version": "0.0.0",\n  "private": true,\n  "main": "./src/index.ts",\n  "scripts": {\n    "lint": "biome lint .",\n    "typecheck": "tsc --noEmit"\n  }\n}\n',
        overwrite: false,
      },
      {
        path: "packages/ui/src/index.ts",
        content: 'export const shared = "shared ui"\n',
        overwrite: false,
      },
    ],
    filesToRemove: [
      "vite.config.ts",
      "vite.config.js",
      "vite.config.mjs",
      "next.config.js",
      "next.config.mjs",
      "next.config.ts",
      "index.html",
      "app/**",
    ],
    dependenciesToAdd: [
      { name: "turbo", version: "^2.0.0", dev: true },
      { name: "next", version: "^16.0.0", dev: false },
      { name: "react", version: "^19.0.0", dev: false },
      { name: "react-dom", version: "^19.0.0", dev: false },
    ],
    scriptsToAdd: {
      "dev:turbo": "pnpm exec turbo dev",
      "build:turbo": "pnpm exec turbo build",
    },
    defaultFeatures: {},
  },
}

export const ALL_FEATURE_IDS = Object.keys(FEATURES) as Array<keyof typeof FEATURES>
export const ALL_PROJECT_TYPE_IDS = Object.keys(PROJECT_TYPES) as Array<keyof typeof PROJECT_TYPES>
